### ISSUE TITLE
Support Remote API v1.16

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ahmetalpbalkan/Docker.DotNet#12]
![](http://cl.ly/image/132F2M1C1s33/Image%202015-01-12%20at%205.56.16%20PM.png)

**Comment by ahmetalpbalkan** [comment]
This version also looks like a good candidate to fix our version number with Remote API's and adopt [semver](http://semver.org) (e.g. v1.16.0) for the library.

**Comment by flipchart** [comment]
I wouldn't suggest setting your version number to the same as the Docker Remote API version. As nice as it is to be able to see quickly what Docker version is supported by Docker.DotNet, it means that you are bound to that version and should only really release when Docker releases a new API version. This means bug fixes and enhancements can only be released when there is a new API version. 

Definitely go with semver, but run your own version numbers, and simply state which version of the API you support in your release notes.

**Comment by ahmetalpbalkan** [comment]
@flipchart I'm not sure why this still does not work out.


> This means bug fixes and enhancements can only be released when there is a new API version.

We can use semver (`MAJOR.MINOR.PATCH`) and MAJOR/MINOR will be the Docker Remote API version and the patch will be used for our iterations and fixes. For instance, when Remote API 1.17 goes out, we'll go as “1.17.0” and fixes to that will go like 1.17.1, 1.17.2 and so on.

> [...] it means that you are bound to that version

Aren't we always bound to some Remote API version? If we happen to make a major change, we can wait and just change the MINOR when a new remote API comes out or use PATCH to release the major change we're making.

But if we are actually going to follow semver compatibility promises and such, we should be probably following our own version as we've been doing until now and we may just release MINOR versions for supporting new Remote API versions. 

On the other hand, I'd really love to keep it human-readable. e.g maybe we can follow 1.116.0, 1.117.0, 1.117.1 so on and introduce major changes as: 2.118, 2.119 by merging MAJORMINOR of the Remote API version. What do you think @flipchart?

**Comment by flipchart** [comment]
This became quite long, forgive the verbosity and opinionatedness - just my thoughts - it's your project, you're free to version how you like :D

Using the patch for bug fixes, etc. *could* work, if you make the assumption that Docker never releases an API with a patch number other than 0. 

> [...] it means that you are bound to that version
> > Aren't we always bound to some Remote API version?

Yes, my point was rather that your version number has to match the Docker API version which is very restrictive and it becomes difficult to convey to *your* users that you have implemented some grant new feature that makes their lives so much easier, but has nothing to do with a change in the API. As an example, if you had implemented the API without `Task<T>` support, and now converted the whole thing to support it, then you would want to release that immediately without waiting for a new Docker API version, and show the importance of it more than using a PATCH number

> [...] we should be probably following our own version

I agree with you, and I think this is the right way to go. 

> [...] by merging MAJORMINOR of the Remote API version

I'm not mad about this. I can definitely see where you are coming from and what you are trying to do, but we should look at the reason for attempting to keep version number parity between Docker.DotNet and the Docker API. The reasoning that I can see is that it allows a consumer of Docker.DotNet to quickly see what the supported version of the Docker API is by looking at the version number. Unfortunately, as I have already seen in the issues for the project, Docker API features get missed (because they couldn't be implemented by the time you wanted to release, or because they weren't documented by Docker). So, even if the version numbers do match, I think that it gives a consumer of Docker.DotNet a false sense of hope that certain features are implemented.

**Comment by ahmetalpbalkan** [comment]
Fair enough, no need to do that. Docker Remote API is not really reliable or backwards compatible all the time. I guess users of the Remote API should have tests around the usages of this library. :smile:

**Comment by ahmetalpbalkan** [comment]
Fixed with #50
