### ISSUE TITLE
Support Remote API 1.18

### ISSUE THREAD

**Issue by ahmetalpbalkan** [ahmetalpbalkan/Docker.DotNet#20]
This is coming up with Docker 1.6 tomorrow.

**Comment by sahus5** [comment]
@ahmetalpbalkan Do you have the link to Docker Remote API 1.18? Can you please share that link.

**Comment by ahmetalpbalkan** [comment]
@sahus5 what do you need from 1.18 specifically? we haven't been updating this library for a while because it handles the basic functionality since 1.13 or so.

**Comment by sahus5** [comment]
In my program I follow these remote API request/response. I am trying to run my program with docker1.6 and it fails because the response of images API have changed. I want to match with those API format.
I can find http://docs.docker.com/reference/api/docker_remote_api_v1.17/ but docker 1.6 supports Client API 1.18
docker version
Client version: 1.6.0
Client API version: 1.18

Is there a way to find this 1.18 API info?

**Comment by ahmetalpbalkan** [comment]
> I am trying to run my program with docker1.6 and it fails because the response of images API have changed.

@sahus5 Please open a separate issue with the error you're seeing.

**Comment by rjperes** [comment]
Docker EXEC, implemented in the pull request for issue #34, is part of API 1.18.

**Comment by ahmetalpbalkan** [comment]
Fixed with #50
